name: Lambda Update

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lambda-update.yml'

jobs:
  update-lambda:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      ECR_REPO: ${{ secrets.ECR_REPO }}
      LAMBDA_NAME: appointment-service-lambda

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Lambda to latest image
        run: |
          IMAGE_URI=$ECR_REPO:latest
          aws lambda update-function-code             --function-name $LAMBDA_NAME             --image-uri $IMAGE_URI
